# Generated by Django 4.1.5 on 2023-01-31 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterField(
            model_name='rocket',
            name='time_launch',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='rocket',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.location', verbose_name='Location'),
        ),
    ]
