# Generated by Django 4.1.5 on 2023-03-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_agency_rocket_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rocket',
            options={'ordering': ['time_launch'], 'verbose_name': 'Rocket', 'verbose_name_plural': 'Rocket'},
        ),
        migrations.AddField(
            model_name='rocket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
