# Generated by Django 4.1.5 on 2023-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_rocket_options_rocket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('family', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Launcher',
                'verbose_name_plural': 'Launcher',
                'ordering': ['title'],
            },
        ),
    ]
