# Generated by Django 4.1.5 on 2023-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_launcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='full_name',
            field=models.CharField(max_length=1255),
        ),
    ]
