# Generated by Django 4.1.5 on 2023-04-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_launcher_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Agency'},
        ),
        migrations.AddField(
            model_name='agency',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='photo',
            field=models.ImageField(default=2023, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
