# Generated by Django 4.1.5 on 2023-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_agency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(db_index=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.TextField(max_length=99),
        ),
    ]
