# Generated by Django 4.1.5 on 2023-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_agency_name_alter_agency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('government', 'Government')], max_length=12),
        ),
    ]
