# Generated by Django 4.1.5 on 2023-04-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_agency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
