# Generated by Django 4.1.5 on 2023-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_location_content_location_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rocket',
            options={'ordering': ['title'], 'verbose_name': 'Rocket', 'verbose_name_plural': 'Rocket'},
        ),
        migrations.RemoveField(
            model_name='rocket',
            name='time_launch',
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=64),
        ),
    ]
