# Generated by Django 4.1.5 on 2023-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_rocket_options_remove_rocket_time_launch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='launcher',
            options={'ordering': ['title'], 'verbose_name': 'Launcher', 'verbose_name_plural': 'Launchers'},
        ),
        migrations.AlterModelOptions(
            name='rocket',
            options={'ordering': ['title'], 'verbose_name': 'Rocket', 'verbose_name_plural': 'Rockets'},
        ),
    ]
