name: PythonAnywhere Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code

        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Deploy to PythonAnywhere
        uses: faustovaz/pythonanywhere-deploy-action@v1
        with:
          api_key: ${{ secrets.PA_API_TOKEN }}
          username: MaxBulgakov
          domain: https://maxbulgakov.pythonanywhere.com/
